language: php

php:
  - 7.1

env:
  global:
    - PHPSTAN=false

matrix:
  fast_finish: true
  include:
    - php: 7.1
    # phpstan
    - php: 7.1
      env: PHPSTAN=true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - travis_retry composer install --prefer-source --no-interaction

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi

script:
  - mkdir -p build/logs
  - if [[ "$PHPSTAN" = false ]]; then vendor/bin/php-cs-fixer fix --verbose --diff --dry-run; fi
  - if [[ "$PHPSTAN" = false ]]; then vendor/bin/phpunit -c phpunit.xml.dist --verbose; fi
  - if [[ "$PHPSTAN" = true ]]; then ./vendor/bin/phpstan analyse -c phpstan.neon -l 6 src/TestingHelper; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover

after_success:
  - if [[ "$PHPSTAN" = false ]]; then bash <(curl -s https://codecov.io/bash); fi